server:
  port: 8080
  servlet:
    context-path: /tdutil

#--- spring config
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  application:
    name: TD Utilities
#   profiles:
#     active: default
#   main:
#     banner-mode: off
  datasource:
    # Configure your datasource here :
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.pool.OracleDataSource
    username: pmo
    password: pmo123
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-pool-name: connectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
#  hikari:
#    schema: XXXX # with Derby schema name = user name
  jpa:
    # Configure JPA-Hibernate here :
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none  # none, update, create, create-drop, validate
    show-sql: true
    open-in-view: false # "Open Session In View" : true by default with Spring
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
#   properties:
#     hibernate.default_schema: XXXX
#
#--- logging config
logging:
  level:
    root: INFO
    org.mweb: DEBUG
#      org.mweb.persistence: DEBUG
#      org.mweb.rest.controllers: DEBUG
#      org.mweb.rest.services: DEBUG