/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.persistence.repositories;

import org.springframework.data.repository.PagingAndSortingRepository;

import com.td.persistence.entities.TaskDependencies;
import java.math.BigDecimal;

/**
 * Spring Data JPA repository for entity "TaskDependencies" <br> 
 * 
 * This repository extends PagingAndSortingRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
public interface TaskDependenciesRepository extends PagingAndSortingRepository<TaskDependencies, BigDecimal> {

	// Insert specific finders here 

	//List<TaskDependencies> findByXxx(String xxx);

	//List<TaskDependencies> findByXxxStartingWith(String xxx);

	//List<TaskDependencies> findByXxxContaining(String xxx);

	//List<TaskDependencies> findByYyy(BigDecimal yyy);

	//List<TaskDependencies> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
