/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.services;

import java.util.List;
import java.util.Optional;

import java.math.BigDecimal;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.td.persistence.entities.TaskDependencies;
import com.td.persistence.repositories.TaskDependenciesRepository;
import com.td.rest.dto.TaskDependenciesDTO;
import com.td.rest.services.commons.GenericService;

/**
 * REST service for entity "TaskDependencies" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class TaskDependenciesService extends GenericService<TaskDependencies, TaskDependenciesDTO> {

	private static final Logger logger = LoggerFactory.getLogger(TaskDependenciesService.class);

	private final TaskDependenciesRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public TaskDependenciesService(TaskDependenciesRepository repository) {
		super(TaskDependencies.class, TaskDependenciesDTO.class);
		this.repository = repository;
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private BigDecimal getEntityId(TaskDependenciesDTO dto) {
		return dto.getDepId();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<TaskDependenciesDTO> findAll() {
		logger.debug("findAll()");
		Iterable<TaskDependencies> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param depId 
	 * @return the entity or null if not found
	 */
	public TaskDependenciesDTO findById(BigDecimal depId) {
		BigDecimal entityId = depId;
		logger.debug("findById({})", entityId);
		Optional<TaskDependencies> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param depId 
	 * @param dto 
	 */
	public void save(BigDecimal depId, TaskDependenciesDTO dto) {
		BigDecimal entityId = depId;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setDepId(depId);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(TaskDependenciesDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param depId 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(BigDecimal depId, TaskDependenciesDTO dto) {
		BigDecimal entityId = depId;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<TaskDependencies> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			TaskDependencies entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(TaskDependenciesDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param depId 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(BigDecimal depId) {
		BigDecimal entityId = depId;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<TaskDependenciesDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<TaskDependencies> list = repository.findByTitle(title);
		List<TaskDependencies> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<TaskDependenciesDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<TaskDependencies> list = repository.findByTitle(title);
		List<TaskDependencies> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<TaskDependenciesDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<TaskDependencies> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}
