/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "ProjectTasks"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="PROJECT_TASKS", schema="PMO" )
public class ProjectTasks implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="TASK_ID", nullable=false)
    private BigDecimal taskId ;

    //--- OTHER DATA FIELDS 
    @Column(name="PROJECT_ID")
    private BigDecimal projectId ;

    @Column(name="TASK_DETAILS", length=500)
    private String     taskDetails ;

    @Column(name="TASK_START")
    private LocalDateTime taskStart ;

    @Column(name="TASK_END")
    private LocalDateTime taskEnd ;

    @Column(name="TASK_ASSIGNMENT", length=200)
    private String     taskAssignment ;

    @Column(name="TASK_DURATION")
    private BigDecimal taskDuration ;

    @Column(name="TASK_COMPLETION")
    private BigDecimal taskCompletion ;

    @Column(name="TASK_RISK_RATING")
    private BigDecimal taskRiskRating ;

    @Column(name="JIRA_REF", length=30)
    private String     jiraRef ;

    @Column(name="TASK_RISK_DETAILS", length=500)
    private String     taskRiskDetails ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PROJECT_ID", referencedColumnName="PROJECT_ID", insertable=false, updatable=false)
    private ProjectMaster projectmaster ; 

    /**
     * Constructor
     */
    public ProjectTasks() {
		super();
    }
    
    public void setTaskId( BigDecimal taskId ) {
        this.taskId = taskId ;
    }
    public BigDecimal getTaskId() {
        return this.taskId;
    }

    public void setProjectId( BigDecimal projectId ) {
        this.projectId = projectId ;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }

    public void setTaskDetails( String taskDetails ) {
        this.taskDetails = taskDetails ;
    }
    public String getTaskDetails() {
        return this.taskDetails;
    }

    public void setTaskStart( LocalDateTime taskStart ) {
        this.taskStart = taskStart ;
    }
    public LocalDateTime getTaskStart() {
        return this.taskStart;
    }

    public void setTaskEnd( LocalDateTime taskEnd ) {
        this.taskEnd = taskEnd ;
    }
    public LocalDateTime getTaskEnd() {
        return this.taskEnd;
    }

    public void setTaskAssignment( String taskAssignment ) {
        this.taskAssignment = taskAssignment ;
    }
    public String getTaskAssignment() {
        return this.taskAssignment;
    }

    public void setTaskDuration( BigDecimal taskDuration ) {
        this.taskDuration = taskDuration ;
    }
    public BigDecimal getTaskDuration() {
        return this.taskDuration;
    }

    public void setTaskCompletion( BigDecimal taskCompletion ) {
        this.taskCompletion = taskCompletion ;
    }
    public BigDecimal getTaskCompletion() {
        return this.taskCompletion;
    }

    public void setTaskRiskRating( BigDecimal taskRiskRating ) {
        this.taskRiskRating = taskRiskRating ;
    }
    public BigDecimal getTaskRiskRating() {
        return this.taskRiskRating;
    }

    public void setJiraRef( String jiraRef ) {
        this.jiraRef = jiraRef ;
    }
    public String getJiraRef() {
        return this.jiraRef;
    }

    public void setTaskRiskDetails( String taskRiskDetails ) {
        this.taskRiskDetails = taskRiskDetails ;
    }
    public String getTaskRiskDetails() {
        return this.taskRiskDetails;
    }

    public ProjectMaster getProjectmaster() {
        return this.projectmaster;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ProjectTasks[");
		sb.append("taskId=").append(taskId);
		sb.append(separator).append("projectId=").append(projectId);
		sb.append(separator).append("taskDetails=").append(taskDetails);
		sb.append(separator).append("taskStart=").append(taskStart);
		sb.append(separator).append("taskEnd=").append(taskEnd);
		sb.append(separator).append("taskAssignment=").append(taskAssignment);
		sb.append(separator).append("taskDuration=").append(taskDuration);
		sb.append(separator).append("taskCompletion=").append(taskCompletion);
		sb.append(separator).append("taskRiskRating=").append(taskRiskRating);
		sb.append(separator).append("jiraRef=").append(jiraRef);
		sb.append(separator).append("taskRiskDetails=").append(taskRiskDetails);
		sb.append("]");
		return sb.toString();
	}

}
