/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import javax.persistence.*;

/**
 * JPA entity class for "SubTasks"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="SUB_TASKS", schema="PMO" )
public class SubTasks implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="SUBTASK_ID", nullable=false)
    private BigDecimal subtaskId ;

    //--- OTHER DATA FIELDS 
    @Column(name="TASK_ID")
    private BigDecimal taskId ;

    @Column(name="SUBTASK_DETAILS", length=500)
    private String     subtaskDetails ;

    @Column(name="SUBTASK_START")
    private LocalDateTime subtaskStart ;

    @Column(name="SUBTASK_END")
    private LocalDateTime subtaskEnd ;

    @Column(name="SUBTASK_ASSIGNMENT", length=200)
    private String     subtaskAssignment ;

    @Column(name="SUBTASK_DURATION")
    private BigDecimal subtaskDuration ;

    @Column(name="SUBTASK_COMPLETION")
    private BigDecimal subtaskCompletion ;

    @Column(name="JIRA_REF", length=30)
    private String     jiraRef ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="TASK_ID", referencedColumnName="TASK_ID", insertable=false, updatable=false)
    private ProjectTasks projecttasks ; 

    /**
     * Constructor
     */
    public SubTasks() {
		super();
    }
    
    public void setSubtaskId( BigDecimal subtaskId ) {
        this.subtaskId = subtaskId ;
    }
    public BigDecimal getSubtaskId() {
        return this.subtaskId;
    }

    public void setTaskId( BigDecimal taskId ) {
        this.taskId = taskId ;
    }
    public BigDecimal getTaskId() {
        return this.taskId;
    }

    public void setSubtaskDetails( String subtaskDetails ) {
        this.subtaskDetails = subtaskDetails ;
    }
    public String getSubtaskDetails() {
        return this.subtaskDetails;
    }

    public void setSubtaskStart( LocalDateTime subtaskStart ) {
        this.subtaskStart = subtaskStart ;
    }
    public LocalDateTime getSubtaskStart() {
        return this.subtaskStart;
    }

    public void setSubtaskEnd( LocalDateTime subtaskEnd ) {
        this.subtaskEnd = subtaskEnd ;
    }
    public LocalDateTime getSubtaskEnd() {
        return this.subtaskEnd;
    }

    public void setSubtaskAssignment( String subtaskAssignment ) {
        this.subtaskAssignment = subtaskAssignment ;
    }
    public String getSubtaskAssignment() {
        return this.subtaskAssignment;
    }

    public void setSubtaskDuration( BigDecimal subtaskDuration ) {
        this.subtaskDuration = subtaskDuration ;
    }
    public BigDecimal getSubtaskDuration() {
        return this.subtaskDuration;
    }

    public void setSubtaskCompletion( BigDecimal subtaskCompletion ) {
        this.subtaskCompletion = subtaskCompletion ;
    }
    public BigDecimal getSubtaskCompletion() {
        return this.subtaskCompletion;
    }

    public void setJiraRef( String jiraRef ) {
        this.jiraRef = jiraRef ;
    }
    public String getJiraRef() {
        return this.jiraRef;
    }

    public ProjectTasks getProjecttasks() {
        return this.projecttasks;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("SubTasks[");
		sb.append("subtaskId=").append(subtaskId);
		sb.append(separator).append("taskId=").append(taskId);
		sb.append(separator).append("subtaskDetails=").append(subtaskDetails);
		sb.append(separator).append("subtaskStart=").append(subtaskStart);
		sb.append(separator).append("subtaskEnd=").append(subtaskEnd);
		sb.append(separator).append("subtaskAssignment=").append(subtaskAssignment);
		sb.append(separator).append("subtaskDuration=").append(subtaskDuration);
		sb.append(separator).append("subtaskCompletion=").append(subtaskCompletion);
		sb.append(separator).append("jiraRef=").append(jiraRef);
		sb.append("]");
		return sb.toString();
	}

}
