/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.persistence.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.*;

/**
 * JPA entity class for "TaskDependencies"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="TASK_DEPENDENCIES", schema="PMO" )
public class TaskDependencies implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="DEP_ID", nullable=false)
    private BigDecimal depId ;

    //--- OTHER DATA FIELDS 
    @Column(name="TASK_TYPE", length=10)
    private String     taskType ;

    @Column(name="TID")
    private BigDecimal tid ;

    @Column(name="DEP_TID")
    private BigDecimal depTid ;

    @Column(name="PROJECT_ID")
    private BigDecimal projectId ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne
    @JoinColumn(name="PROJECT_ID", referencedColumnName="PROJECT_ID", insertable=false, updatable=false)
    private ProjectMaster projectmaster ; 

    /**
     * Constructor
     */
    public TaskDependencies() {
		super();
    }
    
    public void setDepId( BigDecimal depId ) {
        this.depId = depId ;
    }
    public BigDecimal getDepId() {
        return this.depId;
    }

    public void setTaskType( String taskType ) {
        this.taskType = taskType ;
    }
    public String getTaskType() {
        return this.taskType;
    }

    public void setTid( BigDecimal tid ) {
        this.tid = tid ;
    }
    public BigDecimal getTid() {
        return this.tid;
    }

    public void setDepTid( BigDecimal depTid ) {
        this.depTid = depTid ;
    }
    public BigDecimal getDepTid() {
        return this.depTid;
    }

    public void setProjectId( BigDecimal projectId ) {
        this.projectId = projectId ;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }

    public ProjectMaster getProjectmaster() {
        return this.projectmaster;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("TaskDependencies[");
		sb.append("depId=").append(depId);
		sb.append(separator).append("taskType=").append(taskType);
		sb.append(separator).append("tid=").append(tid);
		sb.append(separator).append("depTid=").append(depTid);
		sb.append(separator).append("projectId=").append(projectId);
		sb.append("]");
		return sb.toString();
	}

}
