/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.controllers;

import java.math.BigDecimal;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.td.rest.dto.ProjectTasksDTO;
import com.td.rest.services.ProjectTasksService;

@RestController
@RequestMapping(value = "/api/v1/projecttasks", produces = MediaType.APPLICATION_JSON_VALUE)
public class ProjectTasksRestController {

	private static final Logger logger = LoggerFactory.getLogger(ProjectTasksRestController.class);
	
	private ProjectTasksService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected ProjectTasksRestController(ProjectTasksService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<ProjectTasksDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<ProjectTasksDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param taskId
     * @return 200 or 404 
     */
    @GetMapping("/{taskId}")
    protected ResponseEntity<ProjectTasksDTO> findById(@PathVariable BigDecimal taskId) {
    	logger.debug("REST : GET - findById");
    	ProjectTasksDTO projectTasksDTO = service.findById(taskId);
		if ( projectTasksDTO != null ) {
			return ResponseEntity.ok(projectTasksDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param projectTasksDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody ProjectTasksDTO projectTasksDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(projectTasksDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param taskId
	 * @param projectTasksDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{taskId}")
	protected ResponseEntity<Void> save(@PathVariable BigDecimal taskId, @RequestBody ProjectTasksDTO projectTasksDTO) {
    	logger.debug("REST : PUT - save");
		service.save(taskId, projectTasksDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param projectTasksDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody ProjectTasksDTO projectTasksDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(projectTasksDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param taskId
	 * @param projectTasksDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{taskId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable BigDecimal taskId, @RequestBody ProjectTasksDTO projectTasksDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(taskId, projectTasksDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param taskId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{taskId}")
	protected ResponseEntity<Void> deleteById(@PathVariable BigDecimal taskId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(taskId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
