/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.controllers;

import java.math.BigDecimal;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.td.rest.dto.ProjectMasterDTO;
import com.td.rest.services.ProjectMasterService;

@RestController
@RequestMapping(value = "/api/v1/projectmaster", produces = MediaType.APPLICATION_JSON_VALUE)
public class ProjectMasterRestController {

	private static final Logger logger = LoggerFactory.getLogger(ProjectMasterRestController.class);
	
	private ProjectMasterService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected ProjectMasterRestController(ProjectMasterService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<ProjectMasterDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<ProjectMasterDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param projectId
     * @return 200 or 404 
     */
    @GetMapping("/{projectId}")
    protected ResponseEntity<ProjectMasterDTO> findById(@PathVariable BigDecimal projectId) {
    	logger.debug("REST : GET - findById");
    	ProjectMasterDTO projectMasterDTO = service.findById(projectId);
		if ( projectMasterDTO != null ) {
			return ResponseEntity.ok(projectMasterDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param projectMasterDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody ProjectMasterDTO projectMasterDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(projectMasterDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param projectId
	 * @param projectMasterDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{projectId}")
	protected ResponseEntity<Void> save(@PathVariable BigDecimal projectId, @RequestBody ProjectMasterDTO projectMasterDTO) {
    	logger.debug("REST : PUT - save");
		service.save(projectId, projectMasterDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param projectMasterDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody ProjectMasterDTO projectMasterDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(projectMasterDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param projectId
	 * @param projectMasterDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{projectId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable BigDecimal projectId, @RequestBody ProjectMasterDTO projectMasterDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(projectId, projectMasterDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param projectId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{projectId}")
	protected ResponseEntity<Void> deleteById(@PathVariable BigDecimal projectId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(projectId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
