/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.controllers;

import java.math.BigDecimal;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.td.rest.dto.SubTasksDTO;
import com.td.rest.services.SubTasksService;

@RestController
@RequestMapping(value = "/api/v1/subtasks", produces = MediaType.APPLICATION_JSON_VALUE)
public class SubTasksRestController {

	private static final Logger logger = LoggerFactory.getLogger(SubTasksRestController.class);
	
	private SubTasksService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected SubTasksRestController(SubTasksService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<SubTasksDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<SubTasksDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param subtaskId
     * @return 200 or 404 
     */
    @GetMapping("/{subtaskId}")
    protected ResponseEntity<SubTasksDTO> findById(@PathVariable BigDecimal subtaskId) {
    	logger.debug("REST : GET - findById");
    	SubTasksDTO subTasksDTO = service.findById(subtaskId);
		if ( subTasksDTO != null ) {
			return ResponseEntity.ok(subTasksDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param subTasksDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody SubTasksDTO subTasksDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(subTasksDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param subtaskId
	 * @param subTasksDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{subtaskId}")
	protected ResponseEntity<Void> save(@PathVariable BigDecimal subtaskId, @RequestBody SubTasksDTO subTasksDTO) {
    	logger.debug("REST : PUT - save");
		service.save(subtaskId, subTasksDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param subTasksDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody SubTasksDTO subTasksDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(subTasksDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param subtaskId
	 * @param subTasksDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{subtaskId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable BigDecimal subtaskId, @RequestBody SubTasksDTO subTasksDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(subtaskId, subTasksDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param subtaskId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{subtaskId}")
	protected ResponseEntity<Void> deleteById(@PathVariable BigDecimal subtaskId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(subtaskId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
