/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.controllers;

import java.math.BigDecimal;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.td.rest.dto.TaskDependenciesDTO;
import com.td.rest.services.TaskDependenciesService;

@RestController
@RequestMapping(value = "/api/v1/taskdependencies", produces = MediaType.APPLICATION_JSON_VALUE)
public class TaskDependenciesRestController {

	private static final Logger logger = LoggerFactory.getLogger(TaskDependenciesRestController.class);
	
	private TaskDependenciesService service ; // injected
	
	/**
	 * Constructor (usable for Dependency Injection)
	 *
	 * @param service
	 */
	protected TaskDependenciesRestController(TaskDependenciesService service) {
		super();
		this.service = service;
	}
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<TaskDependenciesDTO>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<TaskDependenciesDTO> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param depId
     * @return 200 or 404 
     */
    @GetMapping("/{depId}")
    protected ResponseEntity<TaskDependenciesDTO> findById(@PathVariable BigDecimal depId) {
    	logger.debug("REST : GET - findById");
    	TaskDependenciesDTO taskDependenciesDTO = service.findById(depId);
		if ( taskDependenciesDTO != null ) {
			return ResponseEntity.ok(taskDependenciesDTO); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param taskDependenciesDTO
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody TaskDependenciesDTO taskDependenciesDTO) {
    	logger.debug("REST : POST - create");
		if ( service.create(taskDependenciesDTO) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param depId
	 * @param taskDependenciesDTO
	 * @return 200 updated or created
	 */
	@PutMapping("/{depId}")
	protected ResponseEntity<Void> save(@PathVariable BigDecimal depId, @RequestBody TaskDependenciesDTO taskDependenciesDTO) {
    	logger.debug("REST : PUT - save");
		service.save(depId, taskDependenciesDTO);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param taskDependenciesDTO
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody TaskDependenciesDTO taskDependenciesDTO) {
    	logger.debug("REST : PUT - update");
		if ( service.update(taskDependenciesDTO) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param depId
	 * @param taskDependenciesDTO
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{depId}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable BigDecimal depId, @RequestBody TaskDependenciesDTO taskDependenciesDTO) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(depId, taskDependenciesDTO) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param depId
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{depId}")
	protected ResponseEntity<Void> deleteById(@PathVariable BigDecimal depId) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(depId) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
