/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * DTO class for "ProjectMaster"
 *
 * @author Telosys
 *
 */
public class ProjectMasterDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private BigDecimal projectId ;
    //--- OTHER DATA FIELDS 
    private String projectSumm ;
    private String projectDesc ;
    private LocalDateTime projectStart ;
    private LocalDateTime projectEnd ;
    private String jiraRef ;
    private BigDecimal projectDuration ;

    /**
     * Constructor
     */
    public ProjectMasterDTO() {
		super();
    }
    
    public void setProjectId( BigDecimal projectId ) {
        this.projectId = projectId ;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }

    public void setProjectSumm( String projectSumm ) {
        this.projectSumm = projectSumm ;
    }
    public String getProjectSumm() {
        return this.projectSumm;
    }

    public void setProjectDesc( String projectDesc ) {
        this.projectDesc = projectDesc ;
    }
    public String getProjectDesc() {
        return this.projectDesc;
    }

    public void setProjectStart( LocalDateTime projectStart ) {
        this.projectStart = projectStart ;
    }
    public LocalDateTime getProjectStart() {
        return this.projectStart;
    }

    public void setProjectEnd( LocalDateTime projectEnd ) {
        this.projectEnd = projectEnd ;
    }
    public LocalDateTime getProjectEnd() {
        return this.projectEnd;
    }

    public void setJiraRef( String jiraRef ) {
        this.jiraRef = jiraRef ;
    }
    public String getJiraRef() {
        return this.jiraRef;
    }

    public void setProjectDuration( BigDecimal projectDuration ) {
        this.projectDuration = projectDuration ;
    }
    public BigDecimal getProjectDuration() {
        return this.projectDuration;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ProjectMaster[");
		sb.append("projectId=").append(projectId);
		sb.append(separator).append("projectSumm=").append(projectSumm);
		sb.append(separator).append("projectDesc=").append(projectDesc);
		sb.append(separator).append("projectStart=").append(projectStart);
		sb.append(separator).append("projectEnd=").append(projectEnd);
		sb.append(separator).append("jiraRef=").append(jiraRef);
		sb.append(separator).append("projectDuration=").append(projectDuration);
		sb.append("]");
		return sb.toString();
	}
}
