/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * DTO class for "ProjectTasks"
 *
 * @author Telosys
 *
 */
public class ProjectTasksDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private BigDecimal taskId ;
    //--- OTHER DATA FIELDS 
    private BigDecimal projectId ;
    private String taskDetails ;
    private LocalDateTime taskStart ;
    private LocalDateTime taskEnd ;
    private String taskAssignment ;
    private BigDecimal taskDuration ;
    private BigDecimal taskCompletion ;
    private BigDecimal taskRiskRating ;
    private String jiraRef ;
    private String taskRiskDetails ;
    //--- LINKS ( RELATIONSHIPS )
    private ProjectMasterDTO projectmaster ; 

    /**
     * Constructor
     */
    public ProjectTasksDTO() {
		super();
    }
    
    public void setTaskId( BigDecimal taskId ) {
        this.taskId = taskId ;
    }
    public BigDecimal getTaskId() {
        return this.taskId;
    }

    public void setProjectId( BigDecimal projectId ) {
        this.projectId = projectId ;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }

    public void setTaskDetails( String taskDetails ) {
        this.taskDetails = taskDetails ;
    }
    public String getTaskDetails() {
        return this.taskDetails;
    }

    public void setTaskStart( LocalDateTime taskStart ) {
        this.taskStart = taskStart ;
    }
    public LocalDateTime getTaskStart() {
        return this.taskStart;
    }

    public void setTaskEnd( LocalDateTime taskEnd ) {
        this.taskEnd = taskEnd ;
    }
    public LocalDateTime getTaskEnd() {
        return this.taskEnd;
    }

    public void setTaskAssignment( String taskAssignment ) {
        this.taskAssignment = taskAssignment ;
    }
    public String getTaskAssignment() {
        return this.taskAssignment;
    }

    public void setTaskDuration( BigDecimal taskDuration ) {
        this.taskDuration = taskDuration ;
    }
    public BigDecimal getTaskDuration() {
        return this.taskDuration;
    }

    public void setTaskCompletion( BigDecimal taskCompletion ) {
        this.taskCompletion = taskCompletion ;
    }
    public BigDecimal getTaskCompletion() {
        return this.taskCompletion;
    }

    public void setTaskRiskRating( BigDecimal taskRiskRating ) {
        this.taskRiskRating = taskRiskRating ;
    }
    public BigDecimal getTaskRiskRating() {
        return this.taskRiskRating;
    }

    public void setJiraRef( String jiraRef ) {
        this.jiraRef = jiraRef ;
    }
    public String getJiraRef() {
        return this.jiraRef;
    }

    public void setTaskRiskDetails( String taskRiskDetails ) {
        this.taskRiskDetails = taskRiskDetails ;
    }
    public String getTaskRiskDetails() {
        return this.taskRiskDetails;
    }

    public ProjectMasterDTO getProjectmaster() {
        return this.projectmaster;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("ProjectTasks[");
		sb.append("taskId=").append(taskId);
		sb.append(separator).append("projectId=").append(projectId);
		sb.append(separator).append("taskDetails=").append(taskDetails);
		sb.append(separator).append("taskStart=").append(taskStart);
		sb.append(separator).append("taskEnd=").append(taskEnd);
		sb.append(separator).append("taskAssignment=").append(taskAssignment);
		sb.append(separator).append("taskDuration=").append(taskDuration);
		sb.append(separator).append("taskCompletion=").append(taskCompletion);
		sb.append(separator).append("taskRiskRating=").append(taskRiskRating);
		sb.append(separator).append("jiraRef=").append(jiraRef);
		sb.append(separator).append("taskRiskDetails=").append(taskRiskDetails);
		sb.append("]");
		return sb.toString();
	}
}
