/*
 * Created on 2025-07-14 ( 12:36:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package com.td.rest.dto;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * DTO class for "TaskDependencies"
 *
 * @author Telosys
 *
 */
public class TaskDependenciesDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private BigDecimal depId ;
    //--- OTHER DATA FIELDS 
    private String taskType ;
    private BigDecimal tid ;
    private BigDecimal depTid ;
    private BigDecimal projectId ;
    //--- LINKS ( RELATIONSHIPS )
    private ProjectMasterDTO projectmaster ; 

    /**
     * Constructor
     */
    public TaskDependenciesDTO() {
		super();
    }
    
    public void setDepId( BigDecimal depId ) {
        this.depId = depId ;
    }
    public BigDecimal getDepId() {
        return this.depId;
    }

    public void setTaskType( String taskType ) {
        this.taskType = taskType ;
    }
    public String getTaskType() {
        return this.taskType;
    }

    public void setTid( BigDecimal tid ) {
        this.tid = tid ;
    }
    public BigDecimal getTid() {
        return this.tid;
    }

    public void setDepTid( BigDecimal depTid ) {
        this.depTid = depTid ;
    }
    public BigDecimal getDepTid() {
        return this.depTid;
    }

    public void setProjectId( BigDecimal projectId ) {
        this.projectId = projectId ;
    }
    public BigDecimal getProjectId() {
        return this.projectId;
    }

    public ProjectMasterDTO getProjectmaster() {
        return this.projectmaster;
    } 

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("TaskDependencies[");
		sb.append("depId=").append(depId);
		sb.append(separator).append("taskType=").append(taskType);
		sb.append(separator).append("tid=").append(tid);
		sb.append(separator).append("depTid=").append(depTid);
		sb.append(separator).append("projectId=").append(projectId);
		sb.append("]");
		return sb.toString();
	}
}
